Seating charts - 2024 edition
cs3157/seatingcharts pull request #35
Opened 2024-03-03 06:04 UTC by carl-vbn

This PR is here to make things a lot easier to work with

- Added `imagedl.py` script to facilitate image downloading
- Added `roster.py` to download rosters. It is also imported by other scripts to standardize roster parsing from CSV files (it can reliably load csv files with or without canvas headers)
- `go_brr` now imports `seatingchart` instead of calling it with `os.system`
- Updated README.md
- A counter of selected seats is now shown on the HTML pages, to make headcounts easier

fixes #32 #26 and starts on #29

2024-03-24 19:27 UTC, tzussman requested changes
Overall this looks really good! I've left a bunch of small comments throughout.
My main concern at the moment is rosters.py -- I didn't take too close of a look at it, but I'm worried that it duplicates functionality that we have in get_class.py in cloud-mgt. More importantly, it looks like it uses a different API endpoint and does some more parsing than get_class does, so I just want to make sure that there aren't some small issues we're missing there (actually it looks like it does it better than get_class so there may be some improvements to make there). It could also do with some more documentation about what format it expects as input and the structure of the roster it returns in Python.

2024-03-24 19:27 UTC, tzussman commented on imagedl.py
> +        percentage = f"{round(counter/uni_count*100, 1)}%"
Could also just calculate the percentage as a number and put in directly in the print below instead of formatting as a string

2024-03-24 19:27 UTC, tzussman commented on imagedl.py
> +        print("Downloading", url, f"({counter}/{uni_count} -- {percentage})")
Would recommend either overwriting the previous line to avoid spamming terminal output or just using tqdm, but not crucial

2024-03-24 19:27 UTC, tzussman commented on imagedl.py
> +            f.write(response.content)
I'd use pathlib over os.path for path stuff -- could also use pathlib.write_bytes() directly here

2024-03-24 19:27 UTC, tzussman commented on imagedl.py
> +    input()
`input()` takes a prompt, can just put the print contents in that using an f-string

2024-03-24 19:27 UTC, tzussman commented on imagedl.py
> +        os.mkdir(output_dir)
Would recommend using pathlib

2024-03-24 19:27 UTC, tzussman commented on imagedl.py
> +            skipped_unis = set(map(lambda file: file.split('.')[0], os.listdir(output_dir))).intersection(unis)
I would use a set comprehension over `set(map())` here if possible: `{file.split('.')[0] for file in os.listdir(output_dir)}` should work (can also use pathlib's iterdir instead)

2024-03-24 19:27 UTC, tzussman commented on imagedl.py
> +    step("The network tab should fill with requests to images named named after student's unis. Right click one of these requests and select 'Copy as cURL (bash)'. Be careful NOT to select the option
I'm not sure how necessary it is to make the user press enter after each step, but for now it's fine -- easy enough to change if necessary

2024-03-24 19:27 UTC, tzussman commented on imagedl.py
> +    url_prefix = "/".join(url.split('/')[:-1])+'/'
Add space between + sign
A comment giving an example of the transformation this is doing would be good (i.e. "Ex: A -> B""

2024-03-24 19:27 UTC, tzussman commented on imagedl.py
> +
Remove one blank line

2024-03-24 19:27 UTC, tzussman commented on imagedl.py
> +def run_guide(output_dir, unis=None, roster_filepath=None, skip_existing=False):
Does run_guide ever get called with unis set? Why do we need it?

2024-03-24 19:27 UTC, tzussman commented on rosters.py
> +    response = list(filter(lambda x: x['sortable_name'] != 'Student, Test', response))
I'm not a big fan of the `list(filter())` style, would prefer a conditional list comprehension instead, but up to you. Same for the instances below

2024-03-24 19:27 UTC, tzussman commented on seatingchart.py
> +import rosters
Same comment about import style as before

2024-03-24 19:27 UTC, tzussman commented on seatingchart.py
> +            csv_output.writerow(list(student) + [seat])
Can probably just do [student, seat] (unless I'm missing something)

2024-03-24 19:27 UTC, tzussman commented on rosters.py
> +
Would be good to have documentation about what format this expects the roster to be in and what format it returns it in -- those have probably been the main source of issues with this repo over the past couple years

2024-03-24 19:27 UTC, tzussman commented on rosters.py
> +            print(RED+"Failed to download roster. Please check your API key and course ID"+END)
Add spaces

2024-03-25 03:51 UTC, chmullig commented on seatingchart.py
> +        seating_chart.write('</table><p class="selected-count-line"><span id="selected-counter">0</span> seats selected.</p></body>')
This is so clever. Wish I'd thought of that!

2024-03-26 01:37 UTC, carl-vbn commented
@tzussman I implemented pretty much all of your feedback.

For rosters.py, I see your point. I added that file because it is very straightforward, not that many moving parts and allows the entire repo to be self-sufficient from retrieving all the files to generating the html. The advantage of the endpoint I'm using is that it returns the entire class in one query (I double checked, the number of entries it gives matches the number of valid rows in the CSV exported from the Grades tab).

If you think we should rely on cloud-mgt instead, I can easily strip the downloading functionality out of it. The file is also used by the other scripts to parse roster files, but none of them use the downloading functionality, that's fully manual. I've also added some more details on why this file is useful vs just loading the CSV in the other files directly.

2024-03-29 23:54 UTC, tzussman reviewed
Left a couple more small comments – this is almost there!
Re: rosters.py, I think it's fine to use it here. In fact, I think you should look into changing the cloud-mgt version to use the endpoint you found, since it seems much simpler.

2024-04-04 23:16 UTC, carl-vbn commented
@tzussman I hope this covers it! I also made rosters.py print things out a bit more nicely using a table, because it was just printing a big blob of unis before.

2024-04-07 03:54 UTC, tzussman approved these changes
This looks great, thanks Carl! Assuming you tested the latest round of updates, feel free to go ahead and merge! (I didn't closely read the `print_table()` code, but I trust that it looks a lot better now)

2024-04-07 22:08 UTC, carl-vbn commented
I tested it all with the last changes before committing, so it should be good to go then. Thanks for all your feedback Tal!

2024-04-07 22:08 UTC, merged